export const SET_TEST_DATA = 'SET_TEST_DATA';

export const SET_QUESTION_DATA = 'SET_QUESTION_DATA';

export const START_TEST = 'START_TEST';

export const CHANGE_ACTIVE_QUESTION = 'CHANGE_ACTIVE_QUESTION';

export const FINISH_TEST = 'FINISH_TEST';

export const UPDATE_QUESTION_ANSWER = 'UPDATE_QUESTION_ANSWER';

export const UPDATE_SUBQUESTION_ID = 'UPDATE_SUBQUESTION_ID';